name: Check Firewalls on Droplets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-firewalls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Run firewall check script
        run: ./check-firewalls.sh